# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_chat_userto'),
    ]

    operations = [
        migrations.CreateModel(
            name='counsallot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('requests', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
