# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0006_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
