# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0008_chat_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='labelc',
            field=models.CharField(default='old', max_length=3),
        ),
    ]
