# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0023_auto_20160711_2352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notifications1',
        ),
    ]
